// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Web.Infrastructure;
using Web.Rounds.Queries;
using Web.Tournaments.Domain;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(DiscmanDbContext))]
    [Migration("20260213150702_UseUtcRoundTimestamps")]
    partial class UseUtcRoundTimestamps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Web.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("Admins")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("admins");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Layout")
                        .HasColumnType("text")
                        .HasColumnName("layout");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("Web.Feeds.Domain.GlobalFeedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AchievementName")
                        .HasColumnType("text")
                        .HasColumnName("achievement_name");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<string>("CourseName")
                        .HasColumnType("text")
                        .HasColumnName("course_name");

                    b.Property<string>("FriendName")
                        .HasColumnType("text")
                        .HasColumnName("friend_name");

                    b.Property<int>("HoleNumber")
                        .HasColumnType("integer")
                        .HasColumnName("hole_number");

                    b.Property<int>("HoleScore")
                        .HasColumnType("integer")
                        .HasColumnName("hole_score");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer")
                        .HasColumnName("item_type");

                    b.PrimitiveCollection<List<string>>("Likes")
                        .HasColumnType("text[]")
                        .HasColumnName("likes");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.PrimitiveCollection<List<int>>("RoundScores")
                        .HasColumnType("integer[]")
                        .HasColumnName("round_scores");

                    b.PrimitiveCollection<List<string>>("Subjects")
                        .HasColumnType("text[]")
                        .HasColumnName("subjects");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid")
                        .HasColumnName("tournament_id");

                    b.Property<string>("TournamentName")
                        .HasColumnType("text")
                        .HasColumnName("tournament_name");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredAt");

                    b.ToTable("global_feed_items", (string)null);
                });

            modelBuilder.Entity("Web.Feeds.Domain.UserFeedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeedItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("feed_item_id");

                    b.Property<int>("ItemType")
                        .HasColumnType("integer")
                        .HasColumnName("item_type");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredAt");

                    b.HasIndex("Username");

                    b.ToTable("user_feed_items", (string)null);
                });

            modelBuilder.Entity("Web.Leaderboard.HallOfFame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.Property<string>("hall_of_fame_type")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.ToTable("hall_of_fames", (string)null);

                    b.HasDiscriminator<string>("hall_of_fame_type").HasValue("base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Web.Rounds.PlayerCourseStats", b =>
                {
                    b.PrimitiveCollection<List<double>>("AveragePrediction")
                        .HasColumnType("double precision[]")
                        .HasColumnName("average_prediction");

                    b.Property<double>("CourseAverage")
                        .HasColumnType("double precision")
                        .HasColumnName("course_average");

                    b.Property<string>("CourseName")
                        .HasColumnType("text")
                        .HasColumnName("course_name");

                    b.PrimitiveCollection<List<double>>("HoleAverages")
                        .HasColumnType("double precision[]")
                        .HasColumnName("hole_averages");

                    b.Property<List<HoleStats>>("HoleStats")
                        .HasColumnType("jsonb")
                        .HasColumnName("hole_stats");

                    b.Property<string>("LayoutName")
                        .HasColumnType("text")
                        .HasColumnName("layout_name");

                    b.Property<int?>("PlayerCourseRecord")
                        .HasColumnType("integer")
                        .HasColumnName("player_course_record");

                    b.Property<string>("PlayerName")
                        .HasColumnType("text")
                        .HasColumnName("player_name");

                    b.Property<int>("RoundsPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("rounds_played");

                    b.Property<double>("ThisRoundVsAverage")
                        .HasColumnType("double precision")
                        .HasColumnName("this_round_vs_average");

                    b.ToTable("player_course_stats", (string)null);
                });

            modelBuilder.Entity("Web.Rounds.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<string>("CourseLayout")
                        .HasColumnType("text")
                        .HasColumnName("course_layout");

                    b.Property<string>("CourseName")
                        .HasColumnType("text")
                        .HasColumnName("course_name");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<string>("RoundName")
                        .HasColumnType("text")
                        .HasColumnName("round_name");

                    b.Property<int>("ScoreMode")
                        .HasColumnType("integer")
                        .HasColumnName("score_mode");

                    b.PrimitiveCollection<List<string>>("Spectators")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("spectators");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.ToTable("rounds", (string)null);
                });

            modelBuilder.Entity("Web.Tournaments.Domain.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("Admins")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("admins");

                    b.PrimitiveCollection<List<Guid>>("Courses")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("courses");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<string>>("Players")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("players");

                    b.Property<TournamentPrices>("Prices")
                        .HasColumnType("jsonb")
                        .HasColumnName("prices");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start");

                    b.HasKey("Id");

                    b.ToTable("tournaments", (string)null);
                });

            modelBuilder.Entity("Web.Users.Domain.ResetPasswordRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("reset_password_requests", (string)null);
                });

            modelBuilder.Entity("Web.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<int>("DiscmanPoints")
                        .HasColumnType("integer")
                        .HasColumnName("discman_points");

                    b.Property<double>("Elo")
                        .HasColumnType("double precision")
                        .HasColumnName("elo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Emoji")
                        .HasColumnType("text")
                        .HasColumnName("emoji");

                    b.PrimitiveCollection<List<string>>("Friends")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("friends");

                    b.Property<DateTime?>("LastEmailSent")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_email_sent");

                    b.PrimitiveCollection<List<string>>("NewsIdsSeen")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("news_ids_seen");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password");

                    b.Property<bool>("RegisterPutDistance")
                        .HasColumnType("boolean")
                        .HasColumnName("register_put_distance");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("salt");

                    b.Property<bool>("SettingsInitialized")
                        .HasColumnType("boolean")
                        .HasColumnName("settings_initialized");

                    b.Property<bool>("SimpleScoring")
                        .HasColumnType("boolean")
                        .HasColumnName("simple_scoring");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Web.Leaderboard.MonthHallOfFame", b =>
                {
                    b.HasBaseType("Web.Leaderboard.HallOfFame");

                    b.HasDiscriminator().HasValue("month");
                });

            modelBuilder.Entity("Web.Courses.Course", b =>
                {
                    b.OwnsOne("Web.Courses.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Latitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("latitude");

                            b1.Property<decimal>("Longitude")
                                .HasPrecision(9, 6)
                                .HasColumnType("numeric(9,6)")
                                .HasColumnName("longitude");

                            b1.HasKey("CourseId");

                            b1.ToTable("courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.OwnsMany("Web.Courses.Hole", "Holes", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<double>("Average")
                                .HasColumnType("double precision")
                                .HasColumnName("average");

                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Distance")
                                .HasColumnType("integer")
                                .HasColumnName("distance");

                            b1.Property<int>("Number")
                                .HasColumnType("integer")
                                .HasColumnName("number");

                            b1.Property<int>("Par")
                                .HasColumnType("integer")
                                .HasColumnName("par");

                            b1.Property<int>("Rating")
                                .HasColumnType("integer")
                                .HasColumnName("rating");

                            b1.HasKey("Id");

                            b1.HasIndex("CourseId");

                            b1.ToTable("course_holes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.Navigation("Coordinates");

                    b.Navigation("Holes");
                });

            modelBuilder.Entity("Web.Leaderboard.HallOfFame", b =>
                {
                    b.OwnsOne("Web.Leaderboard.BestRoundAverage", "BestRoundAverage", b1 =>
                        {
                            b1.Property<Guid>("HallOfFameId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("NewThisMonth")
                                .HasColumnType("boolean")
                                .HasColumnName("best_round_average_new_this_month");

                            b1.Property<double>("RoundAverage")
                                .HasColumnType("double precision")
                                .HasColumnName("best_round_average_round_average");

                            b1.Property<DateTime>("TimeOfEntry")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("best_round_average_time_of_entry");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("best_round_average_username");

                            b1.HasKey("HallOfFameId");

                            b1.ToTable("hall_of_fames");

                            b1.WithOwner()
                                .HasForeignKey("HallOfFameId");
                        });

                    b.OwnsOne("Web.Leaderboard.MostBirdies", "MostBirdies", b1 =>
                        {
                            b1.Property<Guid>("HallOfFameId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Count")
                                .HasColumnType("integer")
                                .HasColumnName("most_birdies_count");

                            b1.Property<bool>("NewThisMonth")
                                .HasColumnType("boolean")
                                .HasColumnName("most_birdies_new_this_month");

                            b1.Property<double>("PerRound")
                                .HasColumnType("double precision")
                                .HasColumnName("most_birdies_per_round");

                            b1.Property<DateTime>("TimeOfEntry")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("most_birdies_time_of_entry");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("most_birdies_username");

                            b1.HasKey("HallOfFameId");

                            b1.ToTable("hall_of_fames");

                            b1.WithOwner()
                                .HasForeignKey("HallOfFameId");
                        });

                    b.OwnsOne("Web.Leaderboard.MostBogies", "MostBogies", b1 =>
                        {
                            b1.Property<Guid>("HallOfFameId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Count")
                                .HasColumnType("integer")
                                .HasColumnName("most_bogies_count");

                            b1.Property<bool>("NewThisMonth")
                                .HasColumnType("boolean")
                                .HasColumnName("most_bogies_new_this_month");

                            b1.Property<double>("PerRound")
                                .HasColumnType("double precision")
                                .HasColumnName("most_bogies_per_round");

                            b1.Property<DateTime>("TimeOfEntry")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("most_bogies_time_of_entry");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("most_bogies_username");

                            b1.HasKey("HallOfFameId");

                            b1.ToTable("hall_of_fames");

                            b1.WithOwner()
                                .HasForeignKey("HallOfFameId");
                        });

                    b.OwnsOne("Web.Leaderboard.MostRounds", "MostRounds", b1 =>
                        {
                            b1.Property<Guid>("HallOfFameId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Count")
                                .HasColumnType("integer")
                                .HasColumnName("most_rounds_count");

                            b1.Property<bool>("NewThisMonth")
                                .HasColumnType("boolean")
                                .HasColumnName("most_rounds_new_this_month");

                            b1.Property<DateTime>("TimeOfEntry")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("most_rounds_time_of_entry");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("most_rounds_username");

                            b1.HasKey("HallOfFameId");

                            b1.ToTable("hall_of_fames");

                            b1.WithOwner()
                                .HasForeignKey("HallOfFameId");
                        });

                    b.Navigation("BestRoundAverage");

                    b.Navigation("MostBirdies");

                    b.Navigation("MostBogies");

                    b.Navigation("MostRounds");
                });

            modelBuilder.Entity("Web.Rounds.Round", b =>
                {
                    b.OwnsMany("Web.Rounds.PlayerScore", "PlayerScores", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<double>("CourseAverageAtTheTime")
                                .HasColumnType("double precision")
                                .HasColumnName("course_average_at_the_time");

                            b1.Property<int>("NumberOfHcpStrokes")
                                .HasColumnType("integer")
                                .HasColumnName("number_of_hcp_strokes");

                            b1.Property<string>("PlayerEmoji")
                                .HasColumnType("text")
                                .HasColumnName("player_emoji");

                            b1.Property<string>("PlayerName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("player_name");

                            b1.Property<string>("PlayerRoundStatusEmoji")
                                .HasColumnType("text")
                                .HasColumnName("player_round_status_emoji");

                            b1.Property<Guid>("RoundId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("RoundId");

                            b1.ToTable("player_scores", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoundId");

                            b1.OwnsMany("Web.Rounds.HoleScore", "Scores", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("PlayerScoreId")
                                        .HasColumnType("integer");

                                    b2.Property<DateTime>("RegisteredAt")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("registered_at");

                                    b2.Property<int>("RelativeToPar")
                                        .HasColumnType("integer")
                                        .HasColumnName("relative_to_par");

                                    b2.Property<int>("Strokes")
                                        .HasColumnType("integer")
                                        .HasColumnName("strokes");

                                    b2.HasKey("Id");

                                    b2.HasIndex("PlayerScoreId");

                                    b2.ToTable("hole_scores", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("PlayerScoreId");

                                    b2.OwnsOne("Web.Courses.Hole", "Hole", b3 =>
                                        {
                                            b3.Property<int>("HoleScoreId")
                                                .HasColumnType("integer");

                                            b3.Property<double>("Average")
                                                .HasColumnType("double precision")
                                                .HasColumnName("hole_average");

                                            b3.Property<int>("Distance")
                                                .HasColumnType("integer")
                                                .HasColumnName("hole_distance");

                                            b3.Property<int>("Number")
                                                .HasColumnType("integer")
                                                .HasColumnName("hole_number");

                                            b3.Property<int>("Par")
                                                .HasColumnType("integer")
                                                .HasColumnName("hole_par");

                                            b3.Property<int>("Rating")
                                                .HasColumnType("integer")
                                                .HasColumnName("hole_rating");

                                            b3.HasKey("HoleScoreId");

                                            b3.ToTable("hole_scores");

                                            b3.WithOwner()
                                                .HasForeignKey("HoleScoreId");
                                        });

                                    b2.OwnsMany("Web.Rounds.StrokeSpec", "StrokeSpecs", b3 =>
                                        {
                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b3.Property<int>("Id"));

                                            b3.Property<int>("HoleScoreId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("Outcome")
                                                .HasColumnType("integer")
                                                .HasColumnName("outcome");

                                            b3.Property<int?>("PutDistance")
                                                .HasColumnType("integer")
                                                .HasColumnName("put_distance");

                                            b3.HasKey("Id");

                                            b3.HasIndex("HoleScoreId");

                                            b3.ToTable("stroke_specs", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("HoleScoreId");
                                        });

                                    b2.Navigation("Hole");

                                    b2.Navigation("StrokeSpecs");
                                });

                            b1.Navigation("Scores");
                        });

                    b.OwnsMany("Web.Rounds.PlayerSignature", "Signatures", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Base64Signature")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("base64_signature");

                            b1.Property<Guid>("RoundId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("SignedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("signed_at");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("username");

                            b1.HasKey("Id");

                            b1.HasIndex("RoundId");

                            b1.ToTable("player_signatures", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoundId");
                        });

                    b.OwnsMany("Web.Rounds.RatingChange", "RatingChanges", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<double>("Change")
                                .HasColumnType("double precision")
                                .HasColumnName("change");

                            b1.Property<Guid>("RoundId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("username");

                            b1.HasKey("Id");

                            b1.HasIndex("RoundId");

                            b1.ToTable("rating_changes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoundId");
                        });

                    b.Navigation("PlayerScores");

                    b.Navigation("RatingChanges");

                    b.Navigation("Signatures");
                });

            modelBuilder.Entity("Web.Users.User", b =>
                {
                    b.OwnsMany("Web.Users.Rating", "RatingHistory", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("DateTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("date_time");

                            b1.Property<double>("Elo")
                                .HasColumnType("double precision")
                                .HasColumnName("elo");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("user_ratings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RatingHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
