// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Web.Infrastructure;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(DiscmanDbContext))]
    partial class DiscmanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Web.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("layout");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Par")
                        .HasColumnType("integer")
                        .HasColumnName("par");

                    b.Property<int>("Plays")
                        .HasColumnType("integer")
                        .HasColumnName("plays");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric")
                        .HasColumnName("rating");

                    b.HasKey("Id");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("Web.Feeds.Domain.GlobalFeedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AchievementName")
                        .HasColumnType("text")
                        .HasColumnName("achievement_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FeedType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feed_type");

                    b.Property<int?>("HoleNumber")
                        .HasColumnType("integer")
                        .HasColumnName("hole_number");

                    b.Property<Guid?>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("global_feed_items", (string)null);
                });

            modelBuilder.Entity("Web.Feeds.Domain.UserFeedItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AchievementName")
                        .HasColumnType("text")
                        .HasColumnName("achievement_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FeedType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feed_type");

                    b.Property<int?>("HoleNumber")
                        .HasColumnType("integer")
                        .HasColumnName("hole_number");

                    b.Property<Guid?>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_feed_items", (string)null);
                });

            modelBuilder.Entity("Web.Leaderboard.HallOfFame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BestScore")
                        .HasColumnType("integer")
                        .HasColumnName("best_score");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("Winner")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("winner");

                    b.HasKey("Id");

                    b.ToTable("hall_of_fames", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("HallOfFame");
                });

            modelBuilder.Entity("Web.Leaderboard.PlayerCourseStats", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<decimal>("AverageScore")
                        .HasColumnType("numeric")
                        .HasColumnName("average_score");

                    b.Property<int>("BestScore")
                        .HasColumnType("integer")
                        .HasColumnName("best_score");

                    b.Property<int>("Plays")
                        .HasColumnType("integer")
                        .HasColumnName("plays");

                    b.ToTable("player_course_stats", (string)null);
                });

            modelBuilder.Entity("Web.Rounds.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Achievements")
                        .HasColumnType("jsonb")
                        .HasColumnName("achievements");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_id");

                    b.Property<string>("CourseLayout")
                        .HasColumnType("text")
                        .HasColumnName("course_layout");

                    b.Property<string>("CourseName")
                        .HasColumnType("text")
                        .HasColumnName("course_name");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<int>("ScoreMode")
                        .HasColumnType("integer")
                        .HasColumnName("score_mode");

                    b.Property<string[]>("Spectators")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("spectators");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("RoundName")
                        .HasColumnType("text")
                        .HasColumnName("round_name");

                    b.HasKey("Id");

                    b.HasQueryFilter((Web.Rounds.Round r) => !r.Deleted);

                    b.ToTable("rounds", (string)null);
                });

            modelBuilder.Entity("Web.Tournaments.Domain.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.ToTable("tournaments", (string)null);
                });

            modelBuilder.Entity("Web.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<int>("DiscmanPoints")
                        .HasColumnType("integer")
                        .HasColumnName("discman_points");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<decimal>("Elo")
                        .HasColumnType("numeric")
                        .HasColumnName("elo");

                    b.Property<string>("Emoji")
                        .HasColumnType("text")
                        .HasColumnName("emoji");

                    b.Property<string[]>("Friends")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("friends");

                    b.Property<DateTime?>("LastEmailSent")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_email_sent");

                    b.Property<string[]>("NewsIdsSeen")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("news_ids_seen");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<bool>("RegisterPutDistance")
                        .HasColumnType("boolean")
                        .HasColumnName("register_put_distance");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("salt");

                    b.Property<bool>("SettingsInitialized")
                        .HasColumnType("boolean")
                        .HasColumnName("settings_initialized");

                    b.Property<bool>("SimpleScoring")
                        .HasColumnType("boolean")
                        .HasColumnName("simple_scoring");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .HasColumnType("xid");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Web.Users.ResetPasswordRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("reset_password_requests", (string)null);
                });

            modelBuilder.Entity("Web.Leaderboard.MonthHallOfFame", b =>
                {
                    b.HasBaseType("Web.Leaderboard.HallOfFame");

                    b.Property<int?>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.HasDiscriminator().HasValue("MonthHallOfFame");
                });

            modelBuilder.Entity("Web.Feeds.Domain.UserFeedItem", b =>
                {
                    b.HasOne("Web.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

#pragma warning restore 612, 618
        }
    }
}
