name: "CI Build"

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    name: Build client and back-end
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: |
          echo "Bulding Discman!"
          sh ./build.sh

  build-image:
    if: startsWith(github.event.ref, 'refs/tags/v')
    name: "Build Docker image"
    runs-on: ubuntu-latest
    needs: build
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/spinakr/discman
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Login to github registry
        if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./src/Web/Dockerfile
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
